#!/bin/bash

# Caddy Local Development Setup Script
# This script sets up Caddy for local development with HTTPS

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to install Caddy
install_caddy() {
    print_status "Installing Caddy..."
    
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        if command_exists brew; then
            brew install caddy
        else
            print_error "Homebrew not found. Please install Homebrew first."
            exit 1
        fi
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        if command_exists apt-get; then
            # Debian/Ubuntu
            sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
            curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
            curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/trusted.gpg.d/caddy-stable.asc
            echo 'deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/debian/ any-version main' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
            sudo apt update
            sudo apt install caddy
        elif command_exists yum; then
            # CentOS/RHEL
            sudo yum install yum-plugin-copr
            sudo yum copr enable @caddy/caddy
            sudo yum install caddy
        else
            print_error "Unsupported Linux distribution. Please install Caddy manually."
            exit 1
        fi
    else
        print_error "Unsupported operating system."
        exit 1
    fi
    
    print_success "Caddy installed successfully"
}

# Function to create Caddyfile
create_caddyfile() {
    local project_dir="$1"
    local domains=("${@:2}")
    
    print_status "Creating Caddyfile in $project_dir..."
    
    cat > "$project_dir/Caddyfile" << EOF
# Caddy configuration for local development
# Auto-generated by setup-caddy-local.sh

EOF

    # Add each domain to Caddyfile
    for domain in "${domains[@]}"; do
        IFS=':' read -r host port <<< "$domain"
        
        cat >> "$project_dir/Caddyfile" << EOF
# $host development server
$host {
    reverse_proxy localhost:$port
    tls internal
}
EOF
    done
    
    print_success "Caddyfile created with domains: ${domains[*]}"
}

# Function to update hosts file
update_hosts_file() {
    local domains=("$@")
    
    print_status "Updating hosts file..."
    
    # Prepare hosts entries
    local hosts_entries=""
    for domain in "${domains[@]}"; do
        IFS=':' read -r host port <<< "$domain"
        hosts_entries="$hosts_entries\n127.0.0.1   $host"
    done
    
    # Update hosts file
    if [[ "$OSTYPE" == "darwin"* ]] || [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # macOS/Linux
        if ! grep -q "# Caddy local domains" /etc/hosts; then
            echo "" | sudo tee -a /etc/hosts > /dev/null
            echo "# Caddy local domains" | sudo tee -a /etc/hosts > /dev/null
        fi
        
        # Remove existing entries for these domains
        for domain in "${domains[@]}"; do
            IFS=':' read -r host port <<< "$domain"
            sudo sed -i '' "/$host/d" /etc/hosts 2>/dev/null || sudo sed -i "/$host/d" /etc/hosts 2>/dev/null || true
        done
        
        # Add new entries
        printf "$hosts_entries\n" | sudo tee -a /etc/hosts > /dev/null
        
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
        # Windows (Git Bash)
        echo "Please manually add the following entries to C:\Windows\System32\drivers\etc\hosts:"
        printf "$hosts_entries\n"
    else
        print_warning "Unsupported OS for automatic hosts file update"
    fi
    
    print_success "Hosts file updated"
}

# Function to flush DNS cache
flush_dns_cache() {
    print_status "Flushing DNS cache..."
    
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sudo dscacheutil -flushcache
        sudo killall -HUP mDNSResponder
        print_success "DNS cache flushed on macOS"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        if command_exists systemd-resolve; then
            sudo systemd-resolve --flush-caches
            print_success "DNS cache flushed on Linux (systemd)"
        elif command_exists service; then
            sudo service nscd restart 2>/dev/null || sudo service nscd reload 2>/dev/null || true
            print_success "DNS cache flushed on Linux (nscd)"
        else
            print_warning "Could not find DNS cache service to flush"
        fi
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
        # Windows
        echo "Run 'ipconfig /flushdns' in Command Prompt as administrator to flush DNS cache"
    fi
}

# Function to start Caddy
start_caddy() {
    local project_dir="$1"
    
    print_status "Starting Caddy in project directory: $project_dir"
    
    cd "$project_dir"
    
    # Check if Caddyfile exists
    if [[ ! -f "Caddyfile" ]]; then
        print_error "Caddyfile not found in $project_dir"
        exit 1
    fi
    
    # Start Caddy in background
    nohup caddy run > caddy.log 2>&1 &
    local caddy_pid=$!
    
    # Wait a moment for Caddy to start
    sleep 2
    
    # Check if Caddy is running
    if kill -0 $caddy_pid 2>/dev/null; then
        print_success "Caddy started successfully (PID: $caddy_pid)"
        echo "$caddy_pid" > .caddy.pid
        echo "Caddy logs: $project_dir/caddy.log"
        echo "To stop Caddy, run: caddy stop"
    else
        print_error "Failed to start Caddy"
        exit 1
    fi
}

# Function to show usage
show_usage() {
    cat << EOF
Usage: $0 [OPTIONS] DOMAIN1:PORT1 [DOMAIN2:PORT2 ...]

Setup Caddy for local development with HTTPS.

OPTIONS:
    -h, --help          Show this help message
    -i, --install       Force install Caddy (even if already installed)
    -p, --project DIR   Use specific project directory (default: current directory)
    --no-start          Don't start Caddy automatically
    --update-hosts      Update hosts file without other operations

EXAMPLES:
    # Setup localhost:3000 and api.localhost:8080
    $0 localhost:3000 api.localhost:8080
    
    # Use specific project directory
    $0 -p /path/to/project web.test:3000 api.web.test:8080
    
    # Force install Caddy and setup
    $0 -i localhost:3000
    
    # Only update hosts file
    $0 --update-hosts localhost:3000 api.localhost:8080

EOF
}

# Parse command line arguments
INSTALL_CADDY=false
PROJECT_DIR="$(pwd)"
START_CADDY=true
UPDATE_ONLY=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_usage
            exit 0
            ;;
        -i|--install)
            INSTALL_CADDY=true
            shift
            ;;
        -p|--project)
            PROJECT_DIR="$2"
            shift 2
            ;;
        --no-start)
            START_CADDY=false
            shift
            ;;
        --update-hosts)
            UPDATE_ONLY=true
            shift
            ;;
        -*)
            print_error "Unknown option: $1"
            show_usage
            exit 1
            ;;
        *)
            DOMAINS+=("$1")
            shift
            ;;
    esac
done

# Check if domains are provided
if [[ ${#DOMAINS[@]} -eq 0 ]] && [[ "$UPDATE_ONLY" == false ]]; then
    print_error "No domains specified"
    show_usage
    exit 1
fi

# Create project directory if it doesn't exist
if [[ ! -d "$PROJECT_DIR" ]]; then
    print_status "Creating project directory: $PROJECT_DIR"
    mkdir -p "$PROJECT_DIR"
fi

# Main execution
main() {
    print_status "Starting Caddy local development setup..."
    
    # Install Caddy if needed or requested
    if [[ "$INSTALL_CADDY" == true ]] || ! command_exists caddy; then
        install_caddy
    else
        print_success "Caddy is already installed"
    fi
    
    if [[ "$UPDATE_ONLY" == true ]]; then
        update_hosts_file "${DOMAINS[@]}"
        flush_dns_cache
        print_success "Hosts file updated successfully"
        exit 0
    fi
    
    # Create Caddyfile
    create_caddyfile "$PROJECT_DIR" "${DOMAINS[@]}"
    
    # Update hosts file
    update_hosts_file "${DOMAINS[@]}"
    
    # Flush DNS cache
    flush_dns_cache
    
    # Start Caddy if requested
    if [[ "$START_CADDY" == true ]]; then
        start_caddy "$PROJECT_DIR"
        
        print_success "Setup complete!"
        echo ""
        echo "Your local domains are now available with HTTPS:"
        for domain in "${DOMAINS[@]}"; do
            IFS=':' read -r host port <<< "$domain"
            echo "  https://$host -> localhost:$port"
        done
        echo ""
        echo "Note: Your browser may show a security warning for self-signed certificates."
        echo "Click 'Proceed anyway' or add a security exception for local development."
    else
        print_success "Setup complete! Run 'caddy run' in $PROJECT_DIR to start the server."
    fi
}

# Run main function
main "$@"